apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GoormPlay/cluster-config.git
    targetRevision: main
    path: global-config
  destination:
    server: https://kubernetes.default.svc
    namespace: config  # 어느 네임스페이스든 상관없음 (그 자체에 배포 X)
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
