{{- range .Values.namespaces }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: global-config
  namespace: {{ . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: global-config
    creationPolicy: Owner
  data:
    - secretKey: SPRING_PROFILES_ACTIVE
      remoteRef:
        key: global/config
        property: SPRING_PROFILES_ACTIVE
    - secretKey: SPRING_SERVER_PORT
      remoteRef:
        key: global/config
        property: SPRING_SERVER_PORT
    - secretKey: S3_FRONTEND_ORIGIN
      remoteRef:
        key: global/config
        property: S3_FRONTEND_ORIGIN
    - secretKey: KAFKA_BOOTSTRAP_SERVERS
      remoteRef:
        key: global/config
        property: KAFKA_BOOTSTRAP_SERVERS
    - secretKey: KAFKA_SCHEMA_REGISTRY_SERVER
      remoteRef:
        key: global/config
        property: KAFKA_SCHEMA_REGISTRY_SERVER
    - secretKey: MONGODB_URI
      remoteRef:
        key: global/config
        property: MONGODB_URI
    - secretKey: MYSQL_HOST
      remoteRef:
        key: global/config
        property: MYSQL_HOST
    - secretKey: MYSQL_PORT
      remoteRef:
        key: global/config
        property: MYSQL_PORT
    - secretKey: MYSQL_USER
      remoteRef:
        key: global/config
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: global/config
        property: MYSQL_PASSWORD
    - secretKey: IMGBB_API_KEY
      remoteRef:
        key: global/config
        property: IMGBB_API_KEY
{{- end }}
