name: Deploy Global Secrets to ArgoCD

on:
  push:
    branches: [ main ]
    paths:
      - global-secret/**
      - argocd/application.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ IRSA_ROLE }}
          aws-region: ap-northeast-2

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ EKS_CLUSTER_NAME }} --region ap-northeast-2

      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f argocd/application.yaml
